#!/usr/bin/env python3
"""Generate diamond-report.md and llm-handoff.json from scan results.

Reads .wrap/diamond-filter.json and .wrap/ip-extract.json,
produces human+LLM readable reports.

Usage:
    python3 util/generate-diamond-report.py wrap/v7/lochan-opencats
"""

import json
import sys
from collections import Counter
from pathlib import Path


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 util/generate-diamond-report.py <package_dir>")
        sys.exit(1)

    pkg_dir = Path(sys.argv[1])
    wrap_dir = pkg_dir / ".wrap"

    if not wrap_dir.exists():
        print(f"No .wrap/ directory in {pkg_dir}")
        sys.exit(1)

    # Load data
    df_path = wrap_dir / "diamond-filter.json"
    ip_path = wrap_dir / "ip-extract.json"

    df = json.loads(df_path.read_text()) if df_path.exists() else {}
    ip = json.loads(ip_path.read_text()) if ip_path.exists() else {}

    pkg_name = ip.get("package", pkg_dir.name.replace("lochan-", ""))

    # Collect all rules
    all_rules = []
    for e in ip.get("extracts", []):
        for r in e.get("extract", {}).get("business_rules", []):
            all_rules.append(r)

    cats = Counter(
        r.get("category", "?") if isinstance(r, dict) else "?"
        for r in all_rules
    )

    noise_keywords = ["valid id", "must be a valid", "fatal", "access level", "permission"]

    def is_noise(rule_text):
        return any(k in rule_text.lower() for k in noise_keywords)

    real_count = sum(1 for r in all_rules
                     if isinstance(r, dict) and not is_noise(r.get("rule", "")))
    noise_count = len(all_rules) - real_count

    # Group by module
    modules = {}
    for e in ip.get("extracts", []):
        route = e.get("route", "")
        clean = route.split(" ")[-1] if " " in route else route
        parts = clean.strip("/").split("/")
        module = parts[0] if parts else "other"
        modules.setdefault(module, []).append(e)

    # ── Build Markdown Report ─────────────────────────────

    md = []
    md.append(f"# {pkg_name.title()} — Diamond Analysis Report")
    md.append("")
    md.append("> Auto-generated by Vardhan Diamond Filter + LLM IP Extraction.")
    md.append("> This document is both a human review artifact and an LLM handoff document.")
    md.append("> An LLM reading this should understand exactly what business logic exists")
    md.append(f"> in {pkg_name} and what needs to be rebuilt vs what the framework replaces.")
    md.append("")

    md.append("## Executive Summary")
    md.append("")
    md.append(f"| Metric | Count |")
    md.append(f"|--------|-------|")
    md.append(f"| Total routes scanned | {ip.get('total_routes', '?')} |")
    md.append(f"| CRUD routes (auto-replaced) | {ip.get('crud_routes', '?')} |")
    md.append(f"| IP routes (non-CRUD) | {ip.get('ip_routes', '?')} |")
    md.append(f"| Diamond candidates (after filter) | {ip.get('diamond_routes', '?')} |")
    md.append(f"| Business rules extracted | {len(all_rules)} |")
    md.append(f"| Real business rules | {real_count} ({real_count * 100 // max(len(all_rules), 1)}%) |")
    md.append(f"| Noise filtered | {noise_count} |")
    md.append("")

    md.append("### Rules by Category")
    md.append("")
    for cat, count in cats.most_common():
        md.append(f"- **{cat}**: {count}")
    md.append("")

    # ── What was filtered ─────────────────────────────────

    md.append("## What Was Filtered Out")
    md.append("")
    md.append("These routes are NOT diamonds — they are handled automatically by the framework:")
    md.append("")

    filtered = df.get("filtered_out", {})
    for cat, items in filtered.items():
        if items:
            label = cat.replace("_", " ").title()
            md.append(f"### {label} ({len(items)} routes)")
            md.append("")
            for item in items[:10]:
                md.append(f"- `{item}`")
            if len(items) > 10:
                md.append(f"- *... and {len(items) - 10} more*")
            md.append("")

    # ── Diamonds by module ────────────────────────────────

    md.append("## Diamonds — Your Business Logic")
    md.append("")
    md.append("Each section below is a module containing real business logic.")
    md.append("The rules are extracted from source code and expressed in plain English.")
    md.append("")

    for module, extracts in sorted(modules.items(), key=lambda x: -len(x[1])):
        # Count real rules in this module
        mod_rules = []
        for e in extracts:
            for r in e.get("extract", {}).get("business_rules", []):
                if isinstance(r, dict) and not is_noise(r.get("rule", "")):
                    mod_rules.append(r)

        md.append(f"### {module.title()} ({len(extracts)} diamonds, {len(mod_rules)} rules)")
        md.append("")

        for e in extracts:
            route = e.get("route", "")
            extract = e.get("extract", {})
            rules = extract.get("business_rules", [])
            deps = extract.get("dependencies", [])
            target = extract.get("lochan_target", "")
            complexity = extract.get("complexity", "low")

            real_rules = [r for r in rules
                          if isinstance(r, dict) and not is_noise(r.get("rule", ""))]

            if not real_rules:
                continue

            md.append(f"#### `{route}`")
            md.append("")
            md.append(f"- **Source**: `{e.get('source_file', '?')}:{e.get('line_number', '?')}`")
            md.append(f"- **Complexity**: {complexity}")
            if target:
                md.append(f"- **Lochan Target**: {target}")
            md.append("")

            md.append("**Business Rules:**")
            md.append("")
            for r in real_rules:
                cat = r.get("category", "")
                rule = r.get("rule", "")
                md.append(f"- **[{cat}]** {rule}")
            md.append("")

            if deps:
                md.append("**Dependencies:**")
                md.append("")
                for d in deps[:5]:
                    md.append(f"- {d}")
                md.append("")

    # ── LLM Handoff ───────────────────────────────────────

    md.append("---")
    md.append("")
    md.append("## LLM Handoff Instructions")
    md.append("")
    md.append("If you are an LLM building or migrating this package:")
    md.append("")
    md.append(f"1. **CRUD routes** ({ip.get('crud_routes', '?')}) → `admin_models` in lochan.json, zero custom code")
    md.append(f"2. **Admin/settings** ({len(filtered.get('admin_config', []))}) → lochan.json + package.py configuration")
    md.append(f"3. **Import/export** ({len(filtered.get('utility', []))}) → standard Lochan import/export utilities")
    md.append(f"4. **Diamonds** ({ip.get('diamond_routes', '?')}) → implement the business rules above:")
    md.append("   - **workflow** rules → Flow workflow templates + state transitions")
    md.append("   - **calculation** rules → service methods with the formulas described")
    md.append("   - **validation** rules → pyCRUD schema validation or custom validators")
    md.append("   - **side_effect** rules → event handlers (email, activity logging)")
    md.append("   - **integration** rules → mandi package adapters")
    md.append("5. Each diamond has **source file + line number** — read the original code for details")
    md.append("6. Each diamond has **dependencies** — these are the services/tables it needs")
    md.append("7. The **Lochan Target** suggests which framework pattern to use")
    md.append("")

    # Write markdown
    report_path = wrap_dir / "diamond-report.md"
    report_path.write_text("\n".join(md))
    print(f"Report:  {report_path} ({len(md)} lines)")

    # ── LLM Handoff JSON ──────────────────────────────────

    llm_handoff = {
        "package": pkg_name,
        "source_stack": "php/php-vanilla",
        "summary": {
            "total_routes": ip.get("total_routes", 0),
            "crud_routes": ip.get("crud_routes", 0),
            "ip_routes": ip.get("ip_routes", 0),
            "diamond_routes": ip.get("diamond_routes", 0),
            "rules_extracted": len(all_rules),
            "real_rules": real_count,
            "precision_pct": real_count * 100 // max(len(all_rules), 1),
        },
        "filtered_out": {
            cat: len(items) for cat, items in filtered.items()
        },
        "modules": {},
    }

    for module, extracts in modules.items():
        mod_rules = []
        for e in extracts:
            for r in e.get("extract", {}).get("business_rules", []):
                if isinstance(r, dict) and not is_noise(r.get("rule", "")):
                    mod_rules.append({
                        "rule": r.get("rule", ""),
                        "category": r.get("category", ""),
                        "route": e.get("route", ""),
                        "source": f"{e.get('source_file', '?')}:{e.get('line_number', '?')}",
                        "lochan_target": e.get("extract", {}).get("lochan_target", ""),
                    })
        if mod_rules:
            llm_handoff["modules"][module] = {
                "diamond_count": len(extracts),
                "rule_count": len(mod_rules),
                "rules": mod_rules,
            }

    handoff_path = wrap_dir / "llm-handoff.json"
    handoff_path.write_text(json.dumps(llm_handoff, indent=2, default=str))
    print(f"Handoff: {handoff_path}")

    # Clean up old files
    old_analysis = wrap_dir / "diamond-filter-analysis.md"
    old_json = wrap_dir / "diamond-filter-analysis.json"
    for old in [old_analysis, old_json]:
        if old.exists():
            old.unlink()
            print(f"Removed old: {old.name}")


if __name__ == "__main__":
    main()
