#!/usr/bin/env bash
# Generated by lochan-drift-hunter 2026-05-14
#
# Pattern 18 (backward-compat residue) + companion patterns drift scanner.
# Founder directive 2026-05-14: "any backward compat or old lingering references —
# delete those. No old folders, no old code, no backward compat."
#
# Usage:
#   ./drift-scan-2026-05-14.sh --all                      # scan everything
#   ./drift-scan-2026-05-14.sh --package <name>           # scan a single package
#   ./drift-scan-2026-05-14.sh --framework                # scan framework only
#   ./drift-scan-2026-05-14.sh --mandi                    # scan mandi only
#
# Exit code:
#   0 — no drift found
#   1 — drift found (CI-pluggable)
#   2 — usage / IO error
#
# Output format:
#   <file>:<line>: <pattern>: <message>: <recommended-fix>

set -o pipefail
# Note: not using `set -u` because some array-expansion patterns below
# (e.g. printf "%s\n" "${pkgs[@]}" when pkgs is empty) trip nounset on older bash.

# Resolve gyanam root: prefer GYANAM_ROOT env var; else derive from script location.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GYANAM_ROOT="${GYANAM_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"

FRAMEWORK_PKG_ROOT="$GYANAM_ROOT/framework/lochan/packages"
MANDI_COMMON_ROOT="$GYANAM_ROOT/mandi/common"
MANDI_DOMAIN_ROOT="$GYANAM_ROOT/mandi/domain"

# Color codes (optional; disabled when not TTY)
if [ -t 1 ]; then
    RED='\033[0;31m'
    YELLOW='\033[0;33m'
    GREEN='\033[0;32m'
    NC='\033[0m'
else
    RED=''
    YELLOW=''
    GREEN=''
    NC=''
fi

DRIFT_COUNT=0
SCOPE_MODE=""
TARGET_PKG=""

# ─────────────────────────────────────────────────────────────
# Argument parsing
# ─────────────────────────────────────────────────────────────

usage() {
    cat <<EOF
Usage: $0 [--all | --framework | --mandi | --package <name>]
  --all          Scan framework + mandi/common + mandi/domain (default)
  --framework    Scan framework/lochan/packages/* only
  --mandi        Scan mandi/common + mandi/domain only
  --package <n>  Scan a single package by name (searches all roots)
EOF
    exit 2
}

case "${1:-}" in
    --all|"") SCOPE_MODE="all" ;;
    --framework) SCOPE_MODE="framework" ;;
    --mandi) SCOPE_MODE="mandi" ;;
    --package)
        SCOPE_MODE="package"
        TARGET_PKG="${2:-}"
        if [ -z "$TARGET_PKG" ]; then
            echo "ERROR: --package requires a package name." >&2
            usage
        fi
        ;;
    -h|--help) usage ;;
    *) echo "ERROR: unknown argument: $1" >&2; usage ;;
esac

# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────

report() {
    # report <severity> <file> <line> <pattern> <message> <fix>
    local sev="$1" file="$2" line="$3" pattern="$4" message="$5" fix="$6"
    local color="$YELLOW"
    case "$sev" in
        HIGH) color="$RED" ;;
        MEDIUM) color="$YELLOW" ;;
        LOW) color="$GREEN" ;;
    esac
    printf "${color}[%s]${NC} %s:%s: %s: %s — FIX: %s\n" \
        "$sev" "$file" "$line" "$pattern" "$message" "$fix"
    DRIFT_COUNT=$((DRIFT_COUNT + 1))
}

# Build the list of package backend dirs to scan based on SCOPE_MODE.
collect_packages() {
    local pkgs=()
    case "$SCOPE_MODE" in
        all|framework)
            for d in "$FRAMEWORK_PKG_ROOT"/*/backend/*/; do
                [ -d "$d" ] || continue
                pkgs+=("$d")
            done
            if [ "$SCOPE_MODE" = "framework" ]; then
                [ ${#pkgs[@]} -gt 0 ] && printf "%s\n" "${pkgs[@]}"
                return
            fi
            ;;
    esac
    case "$SCOPE_MODE" in
        all|mandi)
            for d in "$MANDI_COMMON_ROOT"/*/backend/*/ "$MANDI_DOMAIN_ROOT"/*/backend/*/; do
                [ -d "$d" ] || continue
                pkgs+=("$d")
            done
            ;;
        package)
            for d in "$FRAMEWORK_PKG_ROOT/$TARGET_PKG"/backend/*/ \
                     "$MANDI_COMMON_ROOT/$TARGET_PKG"/backend/*/ \
                     "$MANDI_DOMAIN_ROOT/$TARGET_PKG"/backend/*/; do
                [ -d "$d" ] || continue
                pkgs+=("$d")
            done
            if [ ${#pkgs[@]} -eq 0 ]; then
                echo "ERROR: package '$TARGET_PKG' not found in framework or mandi." >&2
                exit 2
            fi
            ;;
    esac
    [ ${#pkgs[@]} -gt 0 ] && printf "%s\n" "${pkgs[@]}"
}

# ─────────────────────────────────────────────────────────────
# Scan: Pattern 18 — Backward-compat residue
# ─────────────────────────────────────────────────────────────

scan_pattern_18_grep_markers() {
    local pkg_dir="$1"
    # deprecated=True | __lochan_deprecated__ | @deprecated
    while IFS= read -r line; do
        local file=$(echo "$line" | cut -d: -f1)
        local lineno=$(echo "$line" | cut -d: -f2)
        report "HIGH" "$file" "$lineno" "P18-deprecated-marker" \
            "deprecated=True marker still present" \
            "delete the deprecated entry + sweep all consumer references"
    done < <(grep -rn -E "deprecated=True|__lochan_deprecated__|@deprecated" "$pkg_dir" \
                --include="*.py" 2>/dev/null \
                | grep -v __pycache__ \
                | grep -v "build/lib")

    # Comments: # legacy | # backward compat | # transitional | # until V | # for migration | # old path | compatibility shim
    while IFS= read -r line; do
        local file=$(echo "$line" | cut -d: -f1)
        local lineno=$(echo "$line" | cut -d: -f2)
        report "HIGH" "$file" "$lineno" "P18-legacy-comment" \
            "backward-compat comment in code" \
            "delete the legacy branch and the comment in same PR"
    done < <(grep -rn -E "# (legacy|backward.compat|back-compat|transitional|until V|for migration|old path)|compatibility shim" "$pkg_dir" \
                --include="*.py" 2>/dev/null \
                | grep -v __pycache__ \
                | grep -v "build/lib" \
                | grep -v "evolve/checks/backward_compat.py" \
                | grep -v "checks/backward_compat.py" \
                | grep -v "checks/stale_metadata.py")
}

scan_pattern_18_legacy_filenames() {
    local pkg_dir="$1"
    while IFS= read -r f; do
        report "HIGH" "$f" "1" "P18-legacy-filename" \
            "file named with backward-compat suffix" \
            "delete file + sweep callers"
    done < <(find "$pkg_dir" -type f \
                \( -name "*_legacy.py" -o -name "*_old.py" \
                   -o -name "_compat.py" -o -name "_shim.py" \
                   -o -name "*_compat.py" -o -name "*_shim.py" \) \
                2>/dev/null | grep -v __pycache__ | grep -v build/lib)
}

scan_pattern_18_getattr_fallback() {
    local pkg_dir="$1"
    while IFS= read -r line; do
        local file=$(echo "$line" | cut -d: -f1)
        local lineno=$(echo "$line" | cut -d: -f2)
        report "MEDIUM" "$file" "$lineno" "P18-getattr-fallback" \
            "getattr(obj, 'old_attr', new_attr) backward-compat fallback" \
            "remove the legacy attr lookup; require the canonical attr"
    done < <(grep -rn -E "getattr\([^,]+,\s*['\"][a-z_]+['\"]\s*,\s*getattr\(" "$pkg_dir" \
                --include="*.py" 2>/dev/null \
                | grep -v __pycache__ | grep -v build/lib)
}

scan_pattern_18_dual_path_globs() {
    local pkg_dir="$1"
    # Look in pyproject.toml for legacy schemas/* (NOT auto_wire/schemas/*)
    local pyproj="$pkg_dir/../pyproject.toml"
    [ -f "$pyproj" ] || return

    while IFS= read -r line; do
        local lineno=$(echo "$line" | cut -d: -f1)
        local content=$(echo "$line" | cut -d: -f2-)
        report "HIGH" "$pyproj" "$lineno" "P18-dual-path-glob" \
            "pyproject.toml uses legacy '$content' glob — Workstream V dual-path" \
            "git mv backend/<pkg>/<dir> backend/<pkg>/auto_wire/<dir>; update glob to auto_wire/<dir>/*"
    done < <(grep -nE '"(schemas|models|locales|signals|rules|rubrics|taxonomies|policies|scoring_cards)/' "$pyproj" 2>/dev/null \
                | grep -v "auto_wire/" | grep -v "autowire/")
}

# ─────────────────────────────────────────────────────────────
# Scan: Pattern 7 — Empty stub dirs at retired paths
# ─────────────────────────────────────────────────────────────

scan_pattern_7_empty_stub_dirs() {
    local pkg_dir="$1"
    # Find dirs that contain only __pycache__ subdir (no .py files)
    while IFS= read -r d; do
        # Skip pkg root itself
        [ "$d" = "$pkg_dir" ] && continue
        # Skip __pycache__ itself
        case "$d" in *__pycache__*) continue ;; esac
        # Skip tests
        case "$d" in */tests*|*/test_*) continue ;; esac

        # Count non-__pycache__ entries
        local entries=$(find "$d" -mindepth 1 -maxdepth 1 ! -name '__pycache__' 2>/dev/null | wc -l | tr -d ' ')
        if [ "$entries" = "0" ]; then
            # Check if __pycache__ exists with .pyc files (DR-3 archetype)
            if [ -d "$d/__pycache__" ]; then
                local pyc_count=$(find "$d/__pycache__" -name '*.pyc' 2>/dev/null | wc -l | tr -d ' ')
                if [ "$pyc_count" -gt 0 ]; then
                    report "HIGH" "$d" "1" "P7-stale-pycache-mask" \
                        "empty source dir; only stale .pyc files in __pycache__ ($pyc_count files)" \
                        "rm -rf '$d' (after sweeping any '.${d##*/}.' imports to canonical path)"
                else
                    report "MEDIUM" "$d" "1" "P7-empty-stub-dir" \
                        "empty stub directory (only empty __pycache__)" \
                        "rm -rf '$d'"
                fi
            fi
        fi
    done < <(find "$pkg_dir" -type d 2>/dev/null)
}

# ─────────────────────────────────────────────────────────────
# Scan: Pattern 2 — Stale build artifacts
# ─────────────────────────────────────────────────────────────

scan_pattern_2_stale_build() {
    local pkg_dir="$1"
    # Walk up to package root and check for build/ dir
    local backend_root="${pkg_dir%/*/}"  # drops trailing pkg-name/
    local pkg_root="${backend_root%/backend*}"

    for build_path in "$backend_root/build" "$pkg_root/build"; do
        if [ -d "$build_path" ]; then
            local lib_path="$build_path/lib"
            if [ -d "$lib_path" ]; then
                report "MEDIUM" "$build_path" "1" "P2-stale-build-mirror" \
                    "setuptools build/lib/ mirrors source tree (Pattern 2 risk)" \
                    "rm -rf '$build_path' + add build/ to .gitignore"
            else
                report "LOW" "$build_path" "1" "P11-stale-build-dir" \
                    "stale build/ directory (no lib/, but should not be committed)" \
                    "rm -rf '$build_path' + add build/ to .gitignore"
            fi
        fi
    done

    # *.egg-info
    while IFS= read -r d; do
        report "LOW" "$d" "1" "P11-egg-info" \
            "egg-info build artifact committed" \
            "rm -rf '$d' + add *.egg-info to .gitignore"
    done < <(find "$backend_root" -maxdepth 1 -type d -name "*.egg-info" 2>/dev/null)
}

# ─────────────────────────────────────────────────────────────
# Scan: Pattern 13 — Convention non-compliance vs exemplars
# ─────────────────────────────────────────────────────────────

scan_pattern_13_missing_core() {
    local pkg_dir="$1"
    local pkg_name="$(basename "${pkg_dir%/}")"
    if [ ! -d "$pkg_dir/core" ]; then
        report "MEDIUM" "$pkg_dir" "1" "P13-missing-core-dir" \
            "package missing required <pkg>/core/ directory" \
            "create <pkg>/core/ + <pkg>/core/__init__.py; move IP files in (PACKAGE-CONVENTION.md §4 + §11)"
    fi
}

scan_pattern_13_missing_autowire() {
    local pkg_dir="$1"
    if [ ! -d "$pkg_dir/auto_wire" ] && [ ! -d "$pkg_dir/autowire" ]; then
        # Only report if package HAS autowire content (schemas/, models/, etc. at root)
        local has_legacy=0
        for d in schemas models locales signals rules rubrics taxonomies policies; do
            [ -d "$pkg_dir/$d" ] && has_legacy=1 && break
        done
        if [ "$has_legacy" -eq 1 ]; then
            report "MEDIUM" "$pkg_dir" "1" "P13-legacy-autowire-layout" \
                "package has legacy autowire dirs at root instead of auto_wire/ subfolder" \
                "git mv <legacy-dirs> auto_wire/<dirs> (PACKAGE-CONVENTION.md §11 recipe)"
        fi
    fi
}

# ─────────────────────────────────────────────────────────────
# Scan: Pattern 6 — Deprecated convention files
# ─────────────────────────────────────────────────────────────

scan_pattern_6_deprecated_conv_files() {
    local pkg_dir="$1"
    for fname in tools.py event_handlers.py context_provider.py persona_template.py prompt_templates.py lighthouse_provider.py; do
        if [ -f "$pkg_dir/$fname" ]; then
            report "HIGH" "$pkg_dir/$fname" "1" "P6-deprecated-conv-file" \
                "deprecated convention file ($fname) still present" \
                "migrate content to @tool / @on_event / @context decorators on service methods; delete file"
        fi
    done
    # Also: agent_card.py at package root is deprecated (moved to package.py AGENT_CARD dict)
    if [ -f "$pkg_dir/agent_card.py" ]; then
        report "MEDIUM" "$pkg_dir/agent_card.py" "1" "P6-agent-card-redirect" \
            "agent_card.py is a re-export to package.py:AGENT_CARD" \
            "delete agent_card.py; consumers should import from package.AGENT_CARD"
    fi
}

# ─────────────────────────────────────────────────────────────
# Scan: Pattern 7 — Scaffold no-op declarations in package.py
# ─────────────────────────────────────────────────────────────

scan_pattern_7_scaffold_noops() {
    local pkg_dir="$1"
    local pkg_py="$pkg_dir/package.py"
    [ -f "$pkg_py" ] || return
    while IFS= read -r line; do
        local lineno=$(echo "$line" | cut -d: -f1)
        local content=$(echo "$line" | cut -d: -f2-)
        report "MEDIUM" "$pkg_py" "$lineno" "P7-scaffold-noop" \
            "empty literal declaration: $content" \
            "delete the declaration + the convention scanner that requires it"
    done < <(grep -nE "^(GOVERNANCE_CAPABILITIES|app_seeds|EVENTS)\s*=\s*(\{\}|\[\])" "$pkg_py" 2>/dev/null)
}

# ─────────────────────────────────────────────────────────────
# Scan: Pattern 18 — Migrations dirs at non-canonical location
# ─────────────────────────────────────────────────────────────

scan_pattern_18_legacy_migrations() {
    local pkg_dir="$1"
    # migrations/ at PARENT-OF-BACKEND is legacy
    local backend_root="${pkg_dir%/*/}"
    local pkg_root="${backend_root%/backend*}"
    if [ -d "$pkg_root/migrations" ]; then
        report "LOW" "$pkg_root/migrations" "1" "P18-legacy-migrations-dir" \
            "migrations/ at parent-of-backend (pre-V layout)" \
            "delete OR relocate to <pkg>/backend/<pkg>/auto_wire/migrations/ per PACKAGE-CONVENTION.md §11"
    fi
}

# ─────────────────────────────────────────────────────────────
# Scan: Framework-wide — V dual-path resolver runtime fallback
# ─────────────────────────────────────────────────────────────

scan_framework_v_dual_path() {
    local paths_py="$FRAMEWORK_PKG_ROOT/muulam/backend/muulam/std/paths.py"
    [ -f "$paths_py" ] || return
    if grep -q "resolve_autowire_dir\|legacy_path" "$paths_py" 2>/dev/null; then
        local lineno=$(grep -nE "def resolve_autowire_dir" "$paths_py" | head -1 | cut -d: -f1)
        report "HIGH" "$paths_py" "${lineno:-37}" "P18-V-dual-path-runtime" \
            "muulam.std.paths.resolve_autowire_dir contains Workstream V dual-path runtime fallback" \
            "delete the legacy-path branch (lines ~65-80); fail closed when auto_wire/ is missing"
    fi
}

# ─────────────────────────────────────────────────────────────
# Run all scans
# ─────────────────────────────────────────────────────────────

echo "─────────────────────────────────────────────────────────────"
echo "Lochan Drift Scan — $(date +%Y-%m-%d) — scope=$SCOPE_MODE"
echo "─────────────────────────────────────────────────────────────"

# Framework-level singletons (only when scope includes framework)
if [ "$SCOPE_MODE" = "all" ] || [ "$SCOPE_MODE" = "framework" ]; then
    scan_framework_v_dual_path
fi

# Per-package scans
while IFS= read -r pkg_dir; do
    [ -d "$pkg_dir" ] || continue
    # Trim trailing slash for cleaner output
    pkg_dir="${pkg_dir%/}"
    echo ""
    echo "  ── scanning $(basename "$pkg_dir") (${pkg_dir})"
    scan_pattern_18_grep_markers "$pkg_dir"
    scan_pattern_18_legacy_filenames "$pkg_dir"
    scan_pattern_18_getattr_fallback "$pkg_dir"
    scan_pattern_18_dual_path_globs "$pkg_dir"
    scan_pattern_18_legacy_migrations "$pkg_dir"
    scan_pattern_7_empty_stub_dirs "$pkg_dir"
    scan_pattern_2_stale_build "$pkg_dir"
    scan_pattern_13_missing_core "$pkg_dir"
    scan_pattern_13_missing_autowire "$pkg_dir"
    scan_pattern_6_deprecated_conv_files "$pkg_dir"
    scan_pattern_7_scaffold_noops "$pkg_dir"
done < <(collect_packages)

echo ""
echo "─────────────────────────────────────────────────────────────"
if [ "$DRIFT_COUNT" -eq 0 ]; then
    echo -e "${GREEN}CLEAN${NC} — no drift found."
    exit 0
else
    echo -e "${RED}DRIFT FOUND${NC} — $DRIFT_COUNT findings."
    echo "See /Users/srinivasnukala/Dropbox/Sites/claude/lochan/research/drift-report-2026-05-14.md for context."
    exit 1
fi
